import type {
  KnowledgeFeedback,
  KnowledgeItem,
  KnowledgeVersion,
  AppNotification,
} from '@/types';
import { DEMO_COMPANY_ID } from '@/lib/tenant/constants';

const C = DEMO_COMPANY_ID;

export const MOCK_KNOWLEDGE: KnowledgeItem[] = [
  {
    id: 'kn-1',
    company_id: C,
    title: '営業活動ガイドライン 2026',
    content: '見積提出から受注までの標準フロー、承認ルート、禁止事項を定めます。',
    summary: '営業活動の標準フローと承認ルート',
    category: '規定・ルール',
    classification: 'internal',
    department_id: 'dept-1',
    department_name: '営業部',
    tags: ['営業', 'ガイドライン'],
    created_by: 'user-2',
    updated_at: '2026-05-01T10:00:00Z',
    approval_status: 'published',
    version: 3,
    responsible_person_id: 'user-2',
    responsible_person_name: '佐藤 花子',
    updated_by: 'user-2',
    updated_by_name: '佐藤 花子',
    approved_by: 'user-4',
    approved_by_name: '管理者 システム',
  },
  {
    id: 'kn-2',
    company_id: C,
    title: '営業部 顧客対応FAQ',
    content: 'よくある問い合わせと標準回答テンプレート集。',
    summary: '顧客対応のFAQとテンプレート',
    category: 'FAQ',
    classification: 'department',
    department_id: 'dept-1',
    department_name: '営業部',
    tags: ['FAQ', '顧客対応'],
    created_by: 'user-2',
    updated_at: '2025-12-15T14:00:00Z',
    approval_status: 'published',
    version: 2,
    responsible_person_id: 'user-2',
    responsible_person_name: '佐藤 花子',
    updated_by: 'user-2',
    updated_by_name: '佐藤 花子',
    approved_by: 'user-4',
    approved_by_name: '管理者 システム',
  },
  {
    id: 'kn-3',
    company_id: C,
    title: '次期事業計画（機密）',
    content: '役員会資料抜粋。社外秘。配布範囲は経営企画および役員に限定。',
    summary: '次期事業計画の概要',
    category: '経営',
    classification: 'confidential',
    department_id: 'dept-3',
    department_name: '経営企画',
    tags: ['経営', '計画'],
    created_by: 'user-3',
    updated_at: '2026-04-01T09:00:00Z',
    approval_status: 'review',
    version: 1,
    responsible_person_id: 'user-3',
    responsible_person_name: '鈴木 一郎',
    updated_by: 'user-3',
    updated_by_name: '鈴木 一郎',
    approved_by: null,
    approved_by_name: null,
  },
  {
    id: 'kn-4',
    company_id: C,
    title: '役員会議事録サマリー',
    content: '役員限定の意思決定事項とフォローアップ一覧。',
    summary: '役員会の決定事項サマリー',
    category: '経営',
    classification: 'executive_only',
    department_id: 'dept-3',
    department_name: '経営企画',
    tags: ['役員', '議事録'],
    created_by: 'user-3',
    updated_at: '2024-05-01T11:00:00Z',
    approval_status: 'published',
    version: 4,
    responsible_person_id: 'user-3',
    responsible_person_name: '鈴木 一郎',
    updated_by: 'user-3',
    updated_by_name: '鈴木 一郎',
    approved_by: 'user-4',
    approved_by_name: '管理者 システム',
  },
  {
    id: 'kn-5',
    company_id: C,
    title: 'リモートワーク規程（改訂案）',
    content: '週3日出社を基本とするハイブリッド勤務規程の改訂案。',
    summary: 'リモートワーク規程の改訂ドラフト',
    category: '規定・ルール',
    classification: 'internal',
    department_id: null,
    tags: ['人事', '規程'],
    created_by: 'user-4',
    updated_at: '2026-06-01T08:00:00Z',
    approval_status: 'approved',
    version: 2,
    responsible_person_id: 'user-4',
    responsible_person_name: '管理者 システム',
    updated_by: 'user-4',
    updated_by_name: '管理者 システム',
    approved_by: 'user-4',
    approved_by_name: '管理者 システム',
  },
];

export const MOCK_KNOWLEDGE_VERSIONS: KnowledgeVersion[] = [
  {
    id: 'kv-kn-1-v2',
    knowledge_id: 'kn-1',
    company_id: C,
    version: 2,
    title: '営業活動ガイドライン 2026',
    content: '旧版: 見積承認ルートの改訂前',
    summary: '営業活動ガイドライン v2',
    updated_by: 'user-2',
    updated_by_name: '佐藤 花子',
    approved_by: 'user-4',
    approved_by_name: '管理者 システム',
    approval_status: 'published',
    change_reason: '承認ルート改訂',
    created_at: '2026-03-15T10:00:00Z',
  },
];

export const MOCK_FEEDBACK: KnowledgeFeedback[] = [
  {
    id: 'fb-1',
    company_id: C,
    user_id: 'user-1',
    user_name: '山田 太郎',
    question: '見積承認のルールを教えてください',
    answer_summary: '50万円以上は部長承認が必要',
    rating: 'positive',
    chat_message_id: 'm-demo-1',
    created_at: '2026-06-02T10:00:00Z',
  },
  {
    id: 'fb-2',
    company_id: C,
    user_id: 'user-1',
    user_name: '山田 太郎',
    question: '有給の繰越上限は？',
    answer_summary: '該当ナレッジなし',
    rating: 'negative',
    chat_message_id: 'm-demo-2',
    created_at: '2026-06-03T11:30:00Z',
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'ntf-1',
    company_id: C,
    user_id: null,
    type: 'knowledge_published',
    title: 'ナレッジが公開されました',
    message: '「営業活動ガイドライン 2026」が Published になりました（v3）',
    resource_type: 'knowledge_item',
    resource_id: 'kn-1',
    is_read: false,
    created_at: '2026-05-01T12:00:00Z',
  },
  {
    id: 'ntf-2',
    company_id: C,
    user_id: null,
    type: 'knowledge_review',
    title: 'レビュー待ちナレッジ',
    message: '「次期事業計画（機密）」が Review 状態です',
    resource_type: 'knowledge_item',
    resource_id: 'kn-3',
    is_read: true,
    created_at: '2026-04-02T09:00:00Z',
  },
];

/** @deprecated mock-data.ts から re-export */
export { MOCK_KNOWLEDGE as LIFECYCLE_KNOWLEDGE };
