import type { ChatLog } from '@/types';
import { DEMO_COMPANY_ID } from '@/lib/tenant/constants';

const C = DEMO_COMPANY_ID;

export const MOCK_CHAT_LOGS: ChatLog[] = [
  {
    id: 'cl-1',
    company_id: C,
    user_id: 'user-1',
    user_name: '山田 太郎',
    department: '営業部',
    department_id: 'dept-1',
    question: '見積承認のルールを教えてください',
    answer_summary: '営業活動ガイドラインに基づき50万円以上は部長承認が必要です。',
    has_knowledge: true,
    confidence_score: 0.92,
    source_count: 2,
    feedback_result: 'positive',
    unresolved: false,
    resolved_by_admin: false,
    no_knowledge_reason: null,
    status: 'resolved',
    assigned_to_id: null,
    assigned_to_name: null,
    knowledge_item_id: null,
    created_at: '2026-06-01T10:30:00Z',
  },
  {
    id: 'cl-2',
    company_id: C,
    user_id: 'user-1',
    user_name: '山田 太郎',
    department: '営業部',
    department_id: 'dept-1',
    question: '海外向け見積の承認フローは？',
    answer_summary: '該当する社内ナレッジが見つかりませんでした。',
    has_knowledge: false,
    confidence_score: 0.15,
    source_count: 0,
    feedback_result: 'negative',
    unresolved: true,
    resolved_by_admin: false,
    no_knowledge_reason: '海外向け見積に関するナレッジが未整備',
    status: 'open',
    assigned_to_id: null,
    assigned_to_name: null,
    knowledge_item_id: null,
    created_at: '2026-06-02T09:15:00Z',
  },
  {
    id: 'cl-3',
    company_id: C,
    user_id: 'user-2',
    user_name: '佐藤 花子',
    department: '営業部',
    department_id: 'dept-1',
    question: '海外向け見積の承認者は誰ですか',
    answer_summary: '社内資料に該当情報がありません。経理または法務への確認を推奨します。',
    has_knowledge: false,
    confidence_score: 0.22,
    source_count: 0,
    feedback_result: null,
    unresolved: true,
    resolved_by_admin: false,
    no_knowledge_reason: '海外向け見積に関するナレッジが未整備',
    status: 'open',
    assigned_to_id: null,
    assigned_to_name: null,
    knowledge_item_id: null,
    created_at: '2026-06-02T11:00:00Z',
  },
  {
    id: 'cl-4',
    company_id: C,
    user_id: 'user-5',
    user_name: '田中 健',
    department: '開発部',
    department_id: 'dept-2',
    question: '本番デプロイの承認手順を教えて',
    answer_summary: '開発運用マニュアルに記載の3段階承認（リード→部長→インフラ）が必要です。',
    has_knowledge: true,
    confidence_score: 0.88,
    source_count: 1,
    feedback_result: 'positive',
    unresolved: false,
    resolved_by_admin: false,
    no_knowledge_reason: null,
    status: 'resolved',
    assigned_to_id: null,
    assigned_to_name: null,
    knowledge_item_id: null,
    created_at: '2026-06-02T14:00:00Z',
  },
  {
    id: 'cl-5',
    company_id: C,
    user_id: 'user-5',
    user_name: '田中 健',
    department: '開発部',
    department_id: 'dept-2',
    question: 'APIキーのローテーション周期は？',
    answer_summary: '関連ナレッジの最終更新が180日以上前のため、回答の信頼性が低い可能性があります。',
    has_knowledge: true,
    confidence_score: 0.41,
    source_count: 1,
    feedback_result: 'negative',
    unresolved: true,
    resolved_by_admin: false,
    no_knowledge_reason: '古いナレッジ（180日超）のみ参照',
    status: 'assigned',
    assigned_to_id: 'user-2',
    assigned_to_name: '佐藤 花子',
    knowledge_item_id: null,
    created_at: '2026-06-03T08:30:00Z',
  },
  {
    id: 'cl-6',
    company_id: C,
    user_id: 'user-3',
    user_name: '鈴木 一郎',
    department: '経営企画',
    department_id: 'dept-3',
    question: '役員会議の議事録テンプレートはどこ？',
    answer_summary: '経営企画フォルダ内のテンプレート集を参照してください。',
    has_knowledge: true,
    confidence_score: 0.75,
    source_count: 1,
    feedback_result: null,
    unresolved: false,
    resolved_by_admin: false,
    no_knowledge_reason: null,
    status: 'resolved',
    assigned_to_id: null,
    assigned_to_name: null,
    knowledge_item_id: null,
    created_at: '2026-06-03T10:00:00Z',
  },
  {
    id: 'cl-7',
    company_id: C,
    user_id: 'user-1',
    user_name: '山田 太郎',
    department: '営業部',
    department_id: 'dept-1',
    question: '顧客訪問時の服装規定は？',
    answer_summary: '営業活動ガイドライン第3章にスーツ着用・名刺携帯が記載されています。',
    has_knowledge: true,
    confidence_score: 0.85,
    source_count: 1,
    feedback_result: null,
    unresolved: false,
    resolved_by_admin: false,
    no_knowledge_reason: null,
    status: 'resolved',
    assigned_to_id: null,
    assigned_to_name: null,
    knowledge_item_id: null,
    created_at: '2026-06-03T15:20:00Z',
  },
  {
    id: 'cl-8',
    company_id: C,
    user_id: 'user-5',
    user_name: '田中 健',
    department: '開発部',
    department_id: 'dept-2',
    question: 'Slack通知の障害時エスカレーション先は？',
    answer_summary: '該当する社内ナレッジが見つかりませんでした。',
    has_knowledge: false,
    confidence_score: 0.1,
    source_count: 0,
    feedback_result: null,
    unresolved: true,
    resolved_by_admin: false,
    no_knowledge_reason: '障害対応ナレッジ未登録',
    status: 'open',
    assigned_to_id: null,
    assigned_to_name: null,
    knowledge_item_id: null,
    created_at: '2026-06-04T09:00:00Z',
  },
  {
    id: 'cl-9',
    company_id: C,
    user_id: 'user-2',
    user_name: '佐藤 花子',
    department: '営業部',
    department_id: 'dept-1',
    question: 'リードタイムの標準値を教えて',
    answer_summary: '営業部FAQに標準リードタイム2週間と記載（最終更新: 2025年12月）。',
    has_knowledge: true,
    confidence_score: 0.55,
    source_count: 1,
    feedback_result: null,
    unresolved: false,
    resolved_by_admin: false,
    no_knowledge_reason: null,
    status: 'resolved',
    assigned_to_id: null,
    assigned_to_name: null,
    knowledge_item_id: null,
    created_at: '2026-06-04T11:30:00Z',
  },
  {
    id: 'cl-10',
    company_id: C,
    user_id: 'user-3',
    user_name: '鈴木 一郎',
    department: '経営企画',
    department_id: 'dept-3',
    question: 'コンプライアンス研修の受講期限は？',
    answer_summary: '該当する社内ナレッジが見つかりませんでした。',
    has_knowledge: false,
    confidence_score: 0.18,
    source_count: 0,
    feedback_result: 'negative',
    unresolved: true,
    resolved_by_admin: true,
    no_knowledge_reason: '研修ナレッジ未整備',
    status: 'resolved',
    assigned_to_id: 'user-4',
    assigned_to_name: '管理者 システム',
    knowledge_item_id: 'kn-draft-cl10',
    created_at: '2026-05-28T16:00:00Z',
  },
];
